---
- name: Update and upgrade apt
  hosts: servers
  become: true
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes


- name: Reboot server timeout 300s
  hosts: servers
  become: true
  tasks:
    - name: Reboot
      reboot:
        reboot_timeout: 300



